import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../../components/Nav'
import { Box, Grid, GridItem, Heading, SimpleGrid, Text } from '@chakra-ui/react'
import { CollectionsTag, Projects } from '../../components/Alltags'
import { AdvSidebar } from '../../components/Adv'

const AllPost: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Scopri i topic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <SimpleGrid px={30} py={20}>
          <Box>
            <Heading as='h1' size='4xl'>Scopri i topic</Heading>
              <Box pt={3}>
                <Text>
                  Se sei interessanto ad un tops in particolare controlla la sidebare, sicuramente troverei quello che cerchi
                </Text>
              </Box>
          </Box>
        </SimpleGrid>

      <Grid templateColumns='repeat(12, 1fr)' gap={4} p={30}>
      
        <GridItem colSpan={{base: 12, md: 9}} borderTop='1px' borderColor='gray.200' pt={6}>
            <Heading as='h2' fontSize='l' pb={6}>Tutte le news</Heading>
            <Heading as='h2' color='gray.200'>Coming Soon</Heading>
        </GridItem>

        <GridItem colSpan={{base: 12, md: 3}} borderTop='1px' borderColor='gray.200' pt={6}>
            <Box pb={6}>
              <CollectionsTag />
            </Box>
            <Box borderTop='1px' borderColor='gray.200' pt={6} pb={6}>
              <AdvSidebar />
            </Box>
        </GridItem>
        
      </Grid>

    </div>
  )
}

export default AllPost