import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../../components/Nav'
import { SimpleGrid, Heading, Box, Text, Grid, GridItem } from '@chakra-ui/react'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import { title } from 'process';
import CardComponent from '../../components/Card';
import { AdvSidebar } from '../../components/Adv';
import { CollectionsTag, Projects } from '../../components/Alltags';
import Sidebar from '../../components/Sidebar';
import { useRouter } from 'next/router'

export async function getStaticPaths() {
  return {
    paths: [{ params: { title } }],
    fallback: true,
  }
}

export async function getStaticProps(context: { params: any; }) {
  const { params } = context
  const cate = params.title
  const client = new ApolloClient({
    uri: 'https://squid.subsquid.io/subsocial/graphql',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query MyQuery {
        posts(where: {tagsOriginal_contains: "${cate}", AND: {space: {id_eq: "7218"}}}) {
          id
          createdAtTime
          image
          title
          canonical
          downvotesCount
        }
      }
    `
  });

  return {
    props: {
      posts: data.posts
    }
  }
}


const Post: NextPage = (props) => {
  let router = useRouter()
  let titleURL = router.asPath
  let NameH1 = titleURL.split(('/')).pop()
  if (router.isFallback) {
    return <div>Loading...</div>
  }
  return (
    <div>
      <Head>
        <title>Scopri i topic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <SimpleGrid px={30} py={20}>
          <Box>
            <Heading as='h1' size={{base: '2xl', md: '4xl'}}>{NameH1}</Heading>
          </Box>
        </SimpleGrid>

        <Grid templateColumns='repeat(12, 1fr)' gap={4} p={30}>
      
      <GridItem colSpan={{base: 12, md: 9}} borderTop='1px' borderColor='gray.200' pt={6}>
          <Heading as='h2' fontSize='l' pb={6}>Tutte le news</Heading>
          <SimpleGrid columns={{base: 1, md: 3}} spacing={6}>
            {props.posts.map((post: { id: string; title: string; image: string; tags: string[]; }) => 
              <CardComponent id={post.id} title={post.title} cover={post.image} tags={[]} nolike={0} likes={0} body={''} />                    
            )}
          </SimpleGrid>
      </GridItem>

      <GridItem colSpan={{base: 12, md: 3}} borderTop='1px' borderColor='gray.200' pt={6}>
        <Sidebar />
      </GridItem>
      
    </Grid>
    </div>
  )
}

export default Post